services:
  mysql:
    image: mysql:8.0
    container_name: odoru_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odoru
      MYSQL_USER: odoru_user
      MYSQL_PASSWORD: odoru_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: